Repository Corporation-of-Doom/plan-with-doom, pull requests merged in 2018-11, with the labels that each got.

#52 Announcement resolver
  api/src/migrations/002_create_sample_data.sql
  api/src/resolvers/announcement.js
  api/src/types/Announcement.js
Labels: backend, bug

#53 Announcement resolver
  api/src/resolvers/announcement.js
Labels: backend, bug

#74 Display user newsfeed
  api/src/migrations/002_create_sample_data.sql
  frontend/src/views/apps/Timeline.vue
  frontend/src/views/pages/CreateEvent.vue
  frontend/src/views/pages/CreateSeminar.vue
Labels: frontend

#81 Seminar mutation (#78)
  .gitignore
  api/src/mutations/seminar.js
Labels: backend, bug

#82 Closes #79, Added announcement root resolver and fixed queryAnnouncem…
  api/src/resolvers/announcement.js
  api/src/resolvers/index.js
Labels: backend

#89 Manage Events small bug fix
  frontend/src/components/Profile/ProfileEdit.vue
  frontend/src/views/pages/ManageEvents.vue
  frontend/src/views/pages/authentication/Login.vue
Labels: bug, frontend

#92 Event sem bugs
  api/src/migrations/001_create_initial_tables.sql
  api/src/migrations/002_create_sample_data.sql
  api/src/mutations/event.js
  api/src/mutations/seminar.js
  api/src/resolvers/searchResults.js
  api/src/types/Event.js
  api/src/types/Seminar.js
Labels: backend

#96 Detect calendar conflicts
  api/src/resolvers/index.js
  api/src/resolvers/user.js
  api/src/schema.js
Labels: backend

#95 Edit user profile
  api/src/mutations/user.js
Labels: backend

#98 Profile
  api/src/migrations/001_create_initial_tables.sql
  api/src/mutations/index.js
  api/src/mutations/user.js
  api/src/resolvers/index.js
  api/src/resolvers/user.js
  api/src/schema.js
  api/src/types/User.js
  frontend/src/components/Profile/ProfileEdit.vue
  frontend/src/components/Profile/ProfileGallery.vue
  frontend/src/components/Profile/ProfileTimeline.vue
  frontend/src/store.js
  frontend/src/views/apps/Gallery.vue
  frontend/src/views/pages/MyEvents.vue
  frontend/src/views/pages/Profile.vue
  frontend/src/views/pages/authentication/Login.vue
Labels: backend, frontend

#97 Backend: Waitlist
  api/src/migrations/002_create_sample_data.sql
  api/src/mutations/event.js
  api/src/mutations/index.js
  api/src/mutations/seminar.js
  api/src/resolvers/event.js
  api/src/resolvers/index.js
  api/src/resolvers/searchResults.js
  api/src/resolvers/user.js
  api/src/schema.js
  frontend/package-lock.json
  frontend/package.json
Labels: backend

#118 WIP: Edit Event Frontend
  api/src/migrations/002_create_sample_data.sql
  api/src/mutations/event.js
  api/src/mutations/index.js
  api/src/mutations/seminar.js
  api/src/resolvers/event.js
  api/src/resolvers/seminar.js
  api/src/schema.js
  api/src/types/Event.js
  api/src/types/Seminar.js
  frontend/package-lock.json
  frontend/src/components/addEvent.vue
  frontend/src/components/addSeminar.vue
  frontend/src/store.js
  frontend/src/views/pages/CreateEvent.vue
  frontend/src/views/pages/CreateSeminar.vue
  frontend/src/views/pages/Event.vue
  frontend/src/views/pages/Seminar.vue
  frontend/src/views/pages/authentication/Login.vue
  frontend/src/views/pages/helper.js
Labels: backend, frontend
